import React from 'react';
import { SEOHead } from '../components/SEOHead';

export function AboutPage() {
  return (
    <>
      <SEOHead title="About Us" description="Learn more about Free AI Tools Platform and our mission to democratize AI." />
      <div className="prose prose-slate max-w-3xl mx-auto">
        <h1>About Us</h1>
        <p>Welcome to Free AI Tools Platform, your number one source for all things AI generation. We're dedicated to providing you the very best of artificial intelligence tools, with an emphasis on ease of use, accessibility, and quality.</p>
        <p>Founded in 2024, Free AI Tools Platform has come a long way from its beginnings. When we first started out, our passion for "AI for Everyone" drove us to start this business.</p>
        <p>We hope you enjoy our products as much as we enjoy offering them to you. If you have any questions or comments, please don't hesitate to contact us.</p>
      </div>
    </>
  );
}

export function ContactPage() {
  return (
    <>
      <SEOHead title="Contact Us" description="Get in touch with the Free AI Tools Platform team." />
      <div className="max-w-2xl mx-auto">
        <h1 className="text-3xl font-bold mb-6">Contact Us</h1>
        <div className="bg-white p-8 rounded-2xl border border-slate-200 shadow-sm">
          <form className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Name</label>
              <input type="text" className="w-full px-4 py-2 rounded-lg border border-slate-300" />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Email</label>
              <input type="email" className="w-full px-4 py-2 rounded-lg border border-slate-300" />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Message</label>
              <textarea className="w-full px-4 py-2 rounded-lg border border-slate-300 min-h-[150px]"></textarea>
            </div>
            <button className="bg-indigo-600 text-white px-6 py-2 rounded-lg hover:bg-indigo-700">Send Message</button>
          </form>
        </div>
      </div>
    </>
  );
}

export function PrivacyPage() {
  return (
    <>
      <SEOHead title="Privacy Policy" description="Privacy Policy for Free AI Tools Platform." />
      <div className="prose prose-slate max-w-3xl mx-auto">
        <h1>Privacy Policy</h1>
        <p>Last updated: {new Date().toLocaleDateString()}</p>
        <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
        <h2>Collecting and Using Your Personal Data</h2>
        <p>We do not collect any personal data while you use our AI tools. Inputs provided to the AI are processed transiently and are not stored on our servers.</p>
        <h2>Cookies</h2>
        <p>We use Cookies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
      </div>
    </>
  );
}

export function TermsPage() {
  return (
    <>
      <SEOHead title="Terms and Conditions" description="Terms and Conditions for Free AI Tools Platform." />
      <div className="prose prose-slate max-w-3xl mx-auto">
        <h1>Terms and Conditions</h1>
        <p>Please read these terms and conditions carefully before using Our Service.</p>
        <h2>Interpretation and Definitions</h2>
        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions.</p>
        <h2>Acknowledgment</h2>
        <p>These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company.</p>
        <h2>AI Generated Content</h2>
        <p>You acknowledge that content generated by our AI tools may not always be accurate. You are responsible for reviewing and verifying any generated content before use.</p>
      </div>
    </>
  );
}

export function DisclaimerPage() {
  return (
    <>
      <SEOHead title="Disclaimer" description="Disclaimer for Free AI Tools Platform." />
      <div className="prose prose-slate max-w-3xl mx-auto">
        <h1>Disclaimer</h1>
        <p>The information provided by Free AI Tools Platform is for general informational purposes only. All information on the Site is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability or completeness of any information on the Site.</p>
        <h2>External Links Disclaimer</h2>
        <p>The Site may contain (or you may be sent through the Site) links to other websites or content belonging to or originating from third parties or links to websites and features in banners or other advertising.</p>
      </div>
    </>
  );
}
